tooling:
  pip:
    service: python
  python:
    service: python
services:
  python:
    type: python:3.9
    build:
      - 'pip install -r python/requirements.txt'
    run:
      - python python/app.py
    build_as_root:
      - apt-get update
      - apt-get install -y libgl1-mesa-glx libreoffice
proxy:
  python:
    - python.lndo.site:5001
