tooling:
  pip:
    service: python
  python:
    service: python
  flask:
    service: python
    description: Start the Python Flask app for local Python access in Drupal
    cmd: "python web/modules/contrib/dropai/modules/dropai_python/python/app.py"
services:
  python:
    type: python:3.9
    build:
      - 'pip install -r web/modules/contrib/dropai/modules/dropai_python/python/requirements.txt'
    build_as_root:
      - apt-get update
      - apt-get install -y libgl1-mesa-glx libreoffice
    scanner:
      okCodes:
        - 502
proxy:
  python:
    - python.lndo.site:5001
