tooling:
  pip:
    service: python
  python:
    service: python
services:
  python:
    type: python:3.9
    build:
      - 'pip install -r web/modules/contrib/dropai/modules/dropai_python/python/requirements.txt'
    build_as_root:
      - apt-get update
      - apt-get install -y libgl1-mesa-glx libreoffice
proxy:
  python:
    - python.lndo.site:5001
